# Generated by Django 4.0 on 2022-09-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('sub_description', models.TextField(max_length=300, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('cover', models.ImageField(null=True, upload_to='courseCover')),
                ('duration', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('آنلاین', 'ON'), ('آفلاین', 'OFF')], max_length=10)),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_introduction', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourseHeadlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('video_link', models.URLField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
            ],
        ),
    ]
