# Generated by Django 4.0 on 2022-09-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseHeadlines',
            new_name='CourseHeadlinesModel',
        ),
    ]
