# Generated by Django 4.0 on 2022-09-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, null=True)),
                ('right_answer', models.IntegerField(choices=[('گزینه اول', 0), ('گزینه دوم', 1), ('گزینه سوم', 2), ('گزینه چهارم', 3)])),
                ('first_option', models.CharField(max_length=200, null=True)),
                ('second_option', models.CharField(max_length=200, null=True)),
                ('third_option', models.CharField(max_length=200, null=True)),
                ('fourth_option', models.CharField(max_length=200, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
            ],
        ),
    ]
