# Generated by Django 4.0 on 2022-09-10 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='right_answer',
            field=models.IntegerField(choices=[(0, 'گزینه اول'), (1, 'گزینه دوم'), (2, 'گزینه سوم'), (3, 'گزینه چهارم')]),
        ),
        migrations.CreateModel(
            name='UserTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=4, null=True)),
                ('create_at', models.DateTimeField(auto_now=True, null=True)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.testmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
