# Generated by Django 4.0 on 2022-09-10 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_courseheadlines_courseheadlinesmodel'),
        ('test', '0002_alter_testmodel_right_answer_usertests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertests',
            name='test_id',
        ),
        migrations.AddField(
            model_name='usertests',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel'),
        ),
    ]
